<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE HealthData [
<!-- HealthKit Export Version: 11 -->
<!ELEMENT HealthData (ExportDate,Me,(Record|Correlation|Workout|ActivitySummary|ClinicalRecord)*)>
<!ATTLIST HealthData
  locale CDATA #REQUIRED
>
<!ELEMENT ExportDate EMPTY>
<!ATTLIST ExportDate
  value CDATA #REQUIRED
>
<!ELEMENT Me EMPTY>
<!ATTLIST Me
  HKCharacteristicTypeIdentifierDateOfBirth         CDATA #REQUIRED
  HKCharacteristicTypeIdentifierBiologicalSex       CDATA #REQUIRED
  HKCharacteristicTypeIdentifierBloodType           CDATA #REQUIRED
  HKCharacteristicTypeIdentifierFitzpatrickSkinType CDATA #REQUIRED
>
<!ELEMENT Record ((MetadataEntry|HeartRateVariabilityMetadataList)*)>
<!ATTLIST Record
  type          CDATA #REQUIRED
  unit          CDATA #IMPLIED
  value         CDATA #IMPLIED
  sourceName    CDATA #REQUIRED
  sourceVersion CDATA #IMPLIED
  device        CDATA #IMPLIED
  creationDate  CDATA #IMPLIED
  startDate     CDATA #REQUIRED
  endDate       CDATA #REQUIRED
>
<!-- Note: Any Records that appear as children of a correlation also appear as top-level records in this document. -->
<!ELEMENT Correlation ((MetadataEntry|Record)*)>
<!ATTLIST Correlation
  type          CDATA #REQUIRED
  sourceName    CDATA #REQUIRED
  sourceVersion CDATA #IMPLIED
  device        CDATA #IMPLIED
  creationDate  CDATA #IMPLIED
  startDate     CDATA #REQUIRED
  endDate       CDATA #REQUIRED
>
<!ELEMENT Workout ((MetadataEntry|WorkoutEvent|WorkoutRoute)*)>
<!ATTLIST Workout
  workoutActivityType   CDATA #REQUIRED
  duration              CDATA #IMPLIED
  durationUnit          CDATA #IMPLIED
  totalDistance         CDATA #IMPLIED
  totalDistanceUnit     CDATA #IMPLIED
  totalEnergyBurned     CDATA #IMPLIED
  totalEnergyBurnedUnit CDATA #IMPLIED
  sourceName            CDATA #REQUIRED
  sourceVersion         CDATA #IMPLIED
  device                CDATA #IMPLIED
  creationDate          CDATA #IMPLIED
  startDate             CDATA #REQUIRED
  endDate               CDATA #REQUIRED
>
<!ELEMENT WorkoutEvent EMPTY>
<!ATTLIST WorkoutEvent
  type         CDATA #REQUIRED
  date         CDATA #REQUIRED
  duration     CDATA #IMPLIED
  durationUnit CDATA #IMPLIED
>
<!ELEMENT WorkoutRoute ((MetadataEntry|FileReference)*)>
<!ATTLIST WorkoutRoute
  sourceName    CDATA #REQUIRED
  sourceVersion CDATA #IMPLIED
  device        CDATA #IMPLIED
  creationDate  CDATA #IMPLIED
  startDate     CDATA #REQUIRED
  endDate       CDATA #REQUIRED
>
<!ELEMENT FileReference EMPTY>
<!ATTLIST FileReference
  path CDATA #REQUIRED
>
<!ELEMENT ActivitySummary EMPTY>
<!ATTLIST ActivitySummary
  dateComponents           CDATA #IMPLIED
  activeEnergyBurned       CDATA #IMPLIED
  activeEnergyBurnedGoal   CDATA #IMPLIED
  activeEnergyBurnedUnit   CDATA #IMPLIED
  appleMoveTime            CDATA #IMPLIED
  appleMoveTimeGoal        CDATA #IMPLIED
  appleExerciseTime        CDATA #IMPLIED
  appleExerciseTimeGoal    CDATA #IMPLIED
  appleStandHours          CDATA #IMPLIED
  appleStandHoursGoal      CDATA #IMPLIED
>
<!ELEMENT MetadataEntry EMPTY>
<!ATTLIST MetadataEntry
  key   CDATA #REQUIRED
  value CDATA #REQUIRED
>
<!-- Note: Heart Rate Variability records captured by Apple Watch may include an associated list of instantaneous beats-per-minute readings. -->
<!ELEMENT HeartRateVariabilityMetadataList (InstantaneousBeatsPerMinute*)>
<!ELEMENT InstantaneousBeatsPerMinute EMPTY>
<!ATTLIST InstantaneousBeatsPerMinute
  bpm  CDATA #REQUIRED
  time CDATA #REQUIRED
>
<!ELEMENT ClinicalRecord EMPTY>
<!ATTLIST ClinicalRecord
  type              CDATA #REQUIRED
  identifier        CDATA #REQUIRED
  sourceName        CDATA #REQUIRED
  sourceURL         CDATA #REQUIRED
  fhirVersion       CDATA #REQUIRED
  receivedDate      CDATA #REQUIRED
  resourceFilePath  CDATA #REQUIRED
>
<!ELEMENT Audiogram EMPTY>
<!ATTLIST Audiogram
  type          CDATA #REQUIRED
  sourceName    CDATA #REQUIRED
  sourceVersion CDATA #IMPLIED
  device        CDATA #IMPLIED
  creationDate  CDATA #IMPLIED
  startDate     CDATA #REQUIRED
  endDate       CDATA #REQUIRED
>
<!ELEMENT SensitivityPoint EMPTY>
<!ATTLIST SensitivityPoint
  frequencyValue   CDATA #REQUIRED
  frequencyUnit    CDATA #REQUIRED
  leftEarValue     CDATA #IMPLIED
  leftEarUnit      CDATA #IMPLIED
  rightEarValue    CDATA #IMPLIED
  rightEarUnit     CDATA #IMPLIED
>
]>
<HealthData locale="en_VN">
<Record type="HKQuantityTypeIdentifierWalkingAsymmetryPercentage" sourceName="Sample" sourceVersion="14.0" device="&lt;&lt;HKDevice: 0x2811a49b0&gt;, name:iPhone, manufacturer:Apple Inc., model:iPhone, hardware:iPhone12,3, software:14.0&gt;" unit="%" creationDate="2020-09-18 16:46:19 -0800" startDate="2020-09-18 13:14:14 -0800" endDate="2020-09-18 13:14:33 -0800" value="0">
  <MetadataEntry key="HKMetadataKeyDevicePlacementSide" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierWalkingAsymmetryPercentage" sourceName="Sample" sourceVersion="14.0" device="&lt;&lt;HKDevice: 0x2811a49b0&gt;, name:iPhone, manufacturer:Apple Inc., model:iPhone, hardware:iPhone12,3, software:14.0&gt;" unit="%" creationDate="2020-09-18 16:46:19 -0800" startDate="2020-09-18 13:40:55 -0800" endDate="2020-09-18 13:41:47 -0800" value="0">
  <MetadataEntry key="HKMetadataKeyDevicePlacementSide" value="2"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierWalkingAsymmetryPercentage" sourceName="Sample" sourceVersion="14.0" device="&lt;&lt;HKDevice: 0x2811a49b0&gt;, name:iPhone, manufacturer:Apple Inc., model:iPhone, hardware:iPhone12,3, software:14.0&gt;" unit="%" creationDate="2020-09-18 16:46:19 -0800" startDate="2020-09-18 13:43:07 -0800" endDate="2020-09-18 13:43:25 -0800" value="0">
  <MetadataEntry key="HKMetadataKeyDevicePlacementSide" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierWalkingAsymmetryPercentage" sourceName="Sample" sourceVersion="14.0" device="&lt;&lt;HKDevice: 0x2811a49b0&gt;, name:iPhone, manufacturer:Apple Inc., model:iPhone, hardware:iPhone12,3, software:14.0&gt;" unit="%" creationDate="2020-09-18 16:46:19 -0800" startDate="2020-09-18 13:43:49 -0800" endDate="2020-09-18 13:46:03 -0800" value="0.03">
  <MetadataEntry key="HKMetadataKeyDevicePlacementSide" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierWalkingAsymmetryPercentage" sourceName="Sample" sourceVersion="14.0" device="&lt;&lt;HKDevice: 0x2811a49b0&gt;, name:iPhone, manufacturer:Apple Inc., model:iPhone, hardware:iPhone12,3, software:14.0&gt;" unit="%" creationDate="2020-09-23 01:55:17 -0800" startDate="2020-09-22 14:29:07 -0800" endDate="2020-09-22 14:29:59 -0800" value="0.03">
  <MetadataEntry key="HKMetadataKeyDevicePlacementSide" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierWalkingAsymmetryPercentage" sourceName="Sample" sourceVersion="14.0" device="&lt;&lt;HKDevice: 0x2811a49b0&gt;, name:iPhone, manufacturer:Apple Inc., model:iPhone, hardware:iPhone12,3, software:14.0&gt;" unit="%" creationDate="2020-09-23 01:55:17 -0800" startDate="2020-09-22 14:30:24 -0800" endDate="2020-09-22 14:30:56 -0800" value="0">
  <MetadataEntry key="HKMetadataKeyDevicePlacementSide" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierWalkingAsymmetryPercentage" sourceName="Sample" sourceVersion="14.0" device="&lt;&lt;HKDevice: 0x2811a49b0&gt;, name:iPhone, manufacturer:Apple Inc., model:iPhone, hardware:iPhone12,3, software:14.0&gt;" unit="%" creationDate="2020-09-23 01:55:17 -0800" startDate="2020-09-22 14:50:01 -0800" endDate="2020-09-22 14:50:39 -0800" value="0">
  <MetadataEntry key="HKMetadataKeyDevicePlacementSide" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierWalkingAsymmetryPercentage" sourceName="Sample" sourceVersion="14.0" device="&lt;&lt;HKDevice: 0x2811a49b0&gt;, name:iPhone, manufacturer:Apple Inc., model:iPhone, hardware:iPhone12,3, software:14.0&gt;" unit="%" creationDate="2020-09-23 01:55:17 -0800" startDate="2020-09-22 15:34:02 -0800" endDate="2020-09-22 15:34:47 -0800" value="0.04">
  <MetadataEntry key="HKMetadataKeyDevicePlacementSide" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierWalkingAsymmetryPercentage" sourceName="Sample" sourceVersion="14.0" device="&lt;&lt;HKDevice: 0x2811a49b0&gt;, name:iPhone, manufacturer:Apple Inc., model:iPhone, hardware:iPhone12,3, software:14.0&gt;" unit="%" creationDate="2020-09-23 01:55:17 -0800" startDate="2020-09-22 15:52:25 -0800" endDate="2020-09-22 15:52:37 -0800" value="0">
  <MetadataEntry key="HKMetadataKeyDevicePlacementSide" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierWalkingAsymmetryPercentage" sourceName="Sample" sourceVersion="14.0" device="&lt;&lt;HKDevice: 0x2811a49b0&gt;, name:iPhone, manufacturer:Apple Inc., model:iPhone, hardware:iPhone12,3, software:14.0&gt;" unit="%" creationDate="2020-09-23 01:55:17 -0800" startDate="2020-09-22 16:03:40 -0800" endDate="2020-09-22 16:04:06 -0800" value="0">
  <MetadataEntry key="HKMetadataKeyDevicePlacementSide" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierWalkingAsymmetryPercentage" sourceName="Sample" sourceVersion="14.0" device="&lt;&lt;HKDevice: 0x2811a49b0&gt;, name:iPhone, manufacturer:Apple Inc., model:iPhone, hardware:iPhone12,3, software:14.0&gt;" unit="%" creationDate="2020-09-23 01:55:17 -0800" startDate="2020-09-22 16:04:20 -0800" endDate="2020-09-22 16:04:58 -0800" value="0.1">
  <MetadataEntry key="HKMetadataKeyDevicePlacementSide" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierWalkingAsymmetryPercentage" sourceName="Sample" sourceVersion="14.0" device="&lt;&lt;HKDevice: 0x2811a49b0&gt;, name:iPhone, manufacturer:Apple Inc., model:iPhone, hardware:iPhone12,3, software:14.0&gt;" unit="%" creationDate="2020-09-23 01:55:17 -0800" startDate="2020-09-22 16:13:05 -0800" endDate="2020-09-22 16:13:28 -0800" value="0">
  <MetadataEntry key="HKMetadataKeyDevicePlacementSide" value="2"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierWalkingAsymmetryPercentage" sourceName="Sample" sourceVersion="14.0" device="&lt;&lt;HKDevice: 0x2811a49b0&gt;, name:iPhone, manufacturer:Apple Inc., model:iPhone, hardware:iPhone12,3, software:14.0&gt;" unit="%" creationDate="2020-09-23 01:55:17 -0800" startDate="2020-09-22 16:16:25 -0800" endDate="2020-09-22 16:16:46 -0800" value="0">
  <MetadataEntry key="HKMetadataKeyDevicePlacementSide" value="2"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierWalkingAsymmetryPercentage" sourceName="Sample" sourceVersion="14.0" device="&lt;&lt;HKDevice: 0x2811a49b0&gt;, name:iPhone, manufacturer:Apple Inc., model:iPhone, hardware:iPhone12,3, software:14.0&gt;" unit="%" creationDate="2020-09-23 01:55:17 -0800" startDate="2020-09-22 16:17:52 -0800" endDate="2020-09-22 16:18:13 -0800" value="0.27">
  <MetadataEntry key="HKMetadataKeyDevicePlacementSide" value="2"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierWalkingAsymmetryPercentage" sourceName="Sample" sourceVersion="14.0" device="&lt;&lt;HKDevice: 0x2811a49b0&gt;, name:iPhone, manufacturer:Apple Inc., model:iPhone, hardware:iPhone12,3, software:14.0&gt;" unit="%" creationDate="2020-09-23 01:55:17 -0800" startDate="2020-09-22 16:53:16 -0800" endDate="2020-09-22 16:54:07 -0800" value="0">
  <MetadataEntry key="HKMetadataKeyDevicePlacementSide" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierWalkingAsymmetryPercentage" sourceName="Sample" sourceVersion="14.0" device="&lt;&lt;HKDevice: 0x2811a49b0&gt;, name:iPhone, manufacturer:Apple Inc., model:iPhone, hardware:iPhone12,3, software:14.0&gt;" unit="%" creationDate="2020-09-23 01:55:17 -0800" startDate="2020-09-22 16:57:36 -0800" endDate="2020-09-22 16:58:07 -0800" value="0">
  <MetadataEntry key="HKMetadataKeyDevicePlacementSide" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierWalkingAsymmetryPercentage" sourceName="Sample" sourceVersion="14.0" device="&lt;&lt;HKDevice: 0x2811a49b0&gt;, name:iPhone, manufacturer:Apple Inc., model:iPhone, hardware:iPhone12,3, software:14.0&gt;" unit="%" creationDate="2020-09-23 19:39:09 -0800" startDate="2020-09-23 16:18:37 -0800" endDate="2020-09-23 16:19:12 -0800" value="0.08">
  <MetadataEntry key="HKMetadataKeyDevicePlacementSide" value="2"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierWalkingAsymmetryPercentage" sourceName="Sample" sourceVersion="14.0" device="&lt;&lt;HKDevice: 0x2811a49b0&gt;, name:iPhone, manufacturer:Apple Inc., model:iPhone, hardware:iPhone12,3, software:14.0&gt;" unit="%" creationDate="2020-09-23 19:39:09 -0800" startDate="2020-09-23 16:24:36 -0800" endDate="2020-09-23 16:27:57 -0800" value="0">
  <MetadataEntry key="HKMetadataKeyDevicePlacementSide" value="2"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierWalkingAsymmetryPercentage" sourceName="Sample" sourceVersion="14.0" device="&lt;&lt;HKDevice: 0x2811a49b0&gt;, name:iPhone, manufacturer:Apple Inc., model:iPhone, hardware:iPhone12,3, software:14.0&gt;" unit="%" creationDate="2020-09-23 19:39:09 -0800" startDate="2020-09-23 16:28:10 -0800" endDate="2020-09-23 16:29:24 -0800" value="0">
  <MetadataEntry key="HKMetadataKeyDevicePlacementSide" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierWalkingAsymmetryPercentage" sourceName="Sample" sourceVersion="14.0.1" device="&lt;&lt;HKDevice: 0x2811a54f0&gt;, name:iPhone, manufacturer:Apple Inc., model:iPhone, hardware:iPhone12,3, software:14.0.1&gt;" unit="%" creationDate="2020-09-27 21:39:55 -0800" startDate="2020-09-27 11:30:37 -0800" endDate="2020-09-27 11:35:37 -0800" value="0">
  <MetadataEntry key="HKMetadataKeyDevicePlacementSide" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierWalkingAsymmetryPercentage" sourceName="Sample" sourceVersion="14.0.1" device="&lt;&lt;HKDevice: 0x2811a54f0&gt;, name:iPhone, manufacturer:Apple Inc., model:iPhone, hardware:iPhone12,3, software:14.0.1&gt;" unit="%" creationDate="2020-09-27 21:39:55 -0800" startDate="2020-09-27 11:35:38 -0800" endDate="2020-09-27 11:36:08 -0800" value="0">
  <MetadataEntry key="HKMetadataKeyDevicePlacementSide" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierWalkingAsymmetryPercentage" sourceName="Sample" sourceVersion="14.0.1" device="&lt;&lt;HKDevice: 0x2811a54f0&gt;, name:iPhone, manufacturer:Apple Inc., model:iPhone, hardware:iPhone12,3, software:14.0.1&gt;" unit="%" creationDate="2020-09-27 21:39:55 -0800" startDate="2020-09-27 11:42:47 -0800" endDate="2020-09-27 11:42:57 -0800" value="0">
  <MetadataEntry key="HKMetadataKeyDevicePlacementSide" value="2"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierWalkingAsymmetryPercentage" sourceName="Sample" sourceVersion="14.0.1" device="&lt;&lt;HKDevice: 0x2811a54f0&gt;, name:iPhone, manufacturer:Apple Inc., model:iPhone, hardware:iPhone12,3, software:14.0.1&gt;" unit="%" creationDate="2020-09-27 21:39:55 -0800" startDate="2020-09-27 11:56:06 -0800" endDate="2020-09-27 11:56:50 -0800" value="0">
  <MetadataEntry key="HKMetadataKeyDevicePlacementSide" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierWalkingAsymmetryPercentage" sourceName="Sample" sourceVersion="14.0.1" device="&lt;&lt;HKDevice: 0x2811a54f0&gt;, name:iPhone, manufacturer:Apple Inc., model:iPhone, hardware:iPhone12,3, software:14.0.1&gt;" unit="%" creationDate="2020-09-27 21:39:55 -0800" startDate="2020-09-27 12:07:37 -0800" endDate="2020-09-27 12:11:07 -0800" value="0.03">
  <MetadataEntry key="HKMetadataKeyDevicePlacementSide" value="2"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierWalkingAsymmetryPercentage" sourceName="Sample" sourceVersion="14.0.1" device="&lt;&lt;HKDevice: 0x2811a54f0&gt;, name:iPhone, manufacturer:Apple Inc., model:iPhone, hardware:iPhone12,3, software:14.0.1&gt;" unit="%" creationDate="2020-09-27 21:39:55 -0800" startDate="2020-09-27 15:14:52 -0800" endDate="2020-09-27 15:17:42 -0800" value="0.01">
  <MetadataEntry key="HKMetadataKeyDevicePlacementSide" value="2"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierWalkingAsymmetryPercentage" sourceName="Sample" sourceVersion="14.0.1" device="&lt;&lt;HKDevice: 0x2811a54f0&gt;, name:iPhone, manufacturer:Apple Inc., model:iPhone, hardware:iPhone12,3, software:14.0.1&gt;" unit="%" creationDate="2020-09-27 21:39:55 -0800" startDate="2020-09-27 16:23:36 -0800" endDate="2020-09-27 16:24:53 -0800" value="0">
  <MetadataEntry key="HKMetadataKeyDevicePlacementSide" value="2"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierWalkingAsymmetryPercentage" sourceName="Sample" sourceVersion="14.0.1" device="&lt;&lt;HKDevice: 0x2811a54f0&gt;, name:iPhone, manufacturer:Apple Inc., model:iPhone, hardware:iPhone12,3, software:14.0.1&gt;" unit="%" creationDate="2020-09-27 21:39:55 -0800" startDate="2020-09-27 17:20:01 -0800" endDate="2020-09-27 17:20:47 -0800" value="0">
  <MetadataEntry key="HKMetadataKeyDevicePlacementSide" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierWalkingAsymmetryPercentage" sourceName="Sample" sourceVersion="14.0.1" device="&lt;&lt;HKDevice: 0x2811a54f0&gt;, name:iPhone, manufacturer:Apple Inc., model:iPhone, hardware:iPhone12,3, software:14.0.1&gt;" unit="%" creationDate="2020-09-27 21:39:55 -0800" startDate="2020-09-27 17:21:17 -0800" endDate="2020-09-27 17:24:54 -0800" value="0">
  <MetadataEntry key="HKMetadataKeyDevicePlacementSide" value="2"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierWalkingAsymmetryPercentage" sourceName="Sample" sourceVersion="14.0.1" device="&lt;&lt;HKDevice: 0x2811a54f0&gt;, name:iPhone, manufacturer:Apple Inc., model:iPhone, hardware:iPhone12,3, software:14.0.1&gt;" unit="%" creationDate="2020-09-27 21:39:55 -0800" startDate="2020-09-27 17:25:11 -0800" endDate="2020-09-27 17:27:25 -0800" value="0">
  <MetadataEntry key="HKMetadataKeyDevicePlacementSide" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierWalkingAsymmetryPercentage" sourceName="Sample" sourceVersion="14.0.1" device="&lt;&lt;HKDevice: 0x2811a54f0&gt;, name:iPhone, manufacturer:Apple Inc., model:iPhone, hardware:iPhone12,3, software:14.0.1&gt;" unit="%" creationDate="2020-09-27 21:39:55 -0800" startDate="2020-09-27 18:25:47 -0800" endDate="2020-09-27 18:26:42 -0800" value="0">
  <MetadataEntry key="HKMetadataKeyDevicePlacementSide" value="1"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierWalkingAsymmetryPercentage" sourceName="Sample" sourceVersion="14.0.1" device="&lt;&lt;HKDevice: 0x2811a54f0&gt;, name:iPhone, manufacturer:Apple Inc., model:iPhone, hardware:iPhone12,3, software:14.0.1&gt;" unit="%" creationDate="2020-09-27 21:39:55 -0800" startDate="2020-09-27 18:29:17 -0800" endDate="2020-09-27 18:29:57 -0800" value="0.38">
  <MetadataEntry key="HKMetadataKeyDevicePlacementSide" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierWalkingAsymmetryPercentage" sourceName="Sample" sourceVersion="14.0.1" device="&lt;&lt;HKDevice: 0x2811a54f0&gt;, name:iPhone, manufacturer:Apple Inc., model:iPhone, hardware:iPhone12,3, software:14.0.1&gt;" unit="%" creationDate="2020-09-27 21:39:55 -0800" startDate="2020-09-27 19:14:59 -0800" endDate="2020-09-27 19:15:21 -0800" value="0">
  <MetadataEntry key="HKMetadataKeyDevicePlacementSide" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierWalkingAsymmetryPercentage" sourceName="Sample" sourceVersion="14.0.1" device="&lt;&lt;HKDevice: 0x2811a54f0&gt;, name:iPhone, manufacturer:Apple Inc., model:iPhone, hardware:iPhone12,3, software:14.0.1&gt;" unit="%" creationDate="2020-09-27 21:39:55 -0800" startDate="2020-09-27 19:15:40 -0800" endDate="2020-09-27 19:17:10 -0800" value="0">
  <MetadataEntry key="HKMetadataKeyDevicePlacementSide" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierWalkingAsymmetryPercentage" sourceName="Sample" sourceVersion="14.0.1" device="&lt;&lt;HKDevice: 0x2811a54f0&gt;, name:iPhone, manufacturer:Apple Inc., model:iPhone, hardware:iPhone12,3, software:14.0.1&gt;" unit="%" creationDate="2020-09-27 21:39:55 -0800" startDate="2020-09-27 19:17:32 -0800" endDate="2020-09-27 19:17:58 -0800" value="0">
  <MetadataEntry key="HKMetadataKeyDevicePlacementSide" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierWalkingAsymmetryPercentage" sourceName="Sample" sourceVersion="14.0.1" device="&lt;&lt;HKDevice: 0x2811a54f0&gt;, name:iPhone, manufacturer:Apple Inc., model:iPhone, hardware:iPhone12,3, software:14.0.1&gt;" unit="%" creationDate="2020-09-27 21:39:55 -0800" startDate="2020-09-27 19:20:37 -0800" endDate="2020-09-27 19:20:56 -0800" value="0">
  <MetadataEntry key="HKMetadataKeyDevicePlacementSide" value="2"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierWalkingAsymmetryPercentage" sourceName="Sample" sourceVersion="14.0.1" device="&lt;&lt;HKDevice: 0x2811a54f0&gt;, name:iPhone, manufacturer:Apple Inc., model:iPhone, hardware:iPhone12,3, software:14.0.1&gt;" unit="%" creationDate="2020-09-27 21:39:55 -0800" startDate="2020-09-27 20:06:05 -0800" endDate="2020-09-27 20:06:28 -0800" value="0">
  <MetadataEntry key="HKMetadataKeyDevicePlacementSide" value="2"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierWalkingAsymmetryPercentage" sourceName="Sample" sourceVersion="14.0.1" device="&lt;&lt;HKDevice: 0x2811a54f0&gt;, name:iPhone, manufacturer:Apple Inc., model:iPhone, hardware:iPhone12,3, software:14.0.1&gt;" unit="%" creationDate="2020-10-01 02:44:02 -0800" startDate="2020-09-30 13:18:54 -0800" endDate="2020-09-30 13:22:40 -0800" value="0">
  <MetadataEntry key="HKMetadataKeyDevicePlacementSide" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierWalkingAsymmetryPercentage" sourceName="Sample" sourceVersion="14.0.1" device="&lt;&lt;HKDevice: 0x2811a54f0&gt;, name:iPhone, manufacturer:Apple Inc., model:iPhone, hardware:iPhone12,3, software:14.0.1&gt;" unit="%" creationDate="2020-10-01 02:44:02 -0800" startDate="2020-09-30 13:23:40 -0800" endDate="2020-09-30 13:24:15 -0800" value="0.06">
  <MetadataEntry key="HKMetadataKeyDevicePlacementSide" value="1"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierWalkingAsymmetryPercentage" sourceName="Sample" sourceVersion="14.0.1" device="&lt;&lt;HKDevice: 0x2811a54f0&gt;, name:iPhone, manufacturer:Apple Inc., model:iPhone, hardware:iPhone12,3, software:14.0.1&gt;" unit="%" creationDate="2020-10-01 02:44:02 -0800" startDate="2020-09-30 13:47:27 -0800" endDate="2020-09-30 13:50:51 -0800" value="0">
  <MetadataEntry key="HKMetadataKeyDevicePlacementSide" value="2"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierWalkingAsymmetryPercentage" sourceName="Sample" sourceVersion="14.0.1" device="&lt;&lt;HKDevice: 0x2811a54f0&gt;, name:iPhone, manufacturer:Apple Inc., model:iPhone, hardware:iPhone12,3, software:14.0.1&gt;" unit="%" creationDate="2020-10-01 02:44:02 -0800" startDate="2020-09-30 18:09:14 -0800" endDate="2020-09-30 18:11:59 -0800" value="0">
  <MetadataEntry key="HKMetadataKeyDevicePlacementSide" value="2"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierWalkingAsymmetryPercentage" sourceName="Sample" sourceVersion="14.0.1" device="&lt;&lt;HKDevice: 0x2811a54f0&gt;, name:iPhone, manufacturer:Apple Inc., model:iPhone, hardware:iPhone12,3, software:14.0.1&gt;" unit="%" creationDate="2020-10-01 02:44:02 -0800" startDate="2020-09-30 18:14:01 -0800" endDate="2020-09-30 18:14:31 -0800" value="0">
  <MetadataEntry key="HKMetadataKeyDevicePlacementSide" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierWalkingAsymmetryPercentage" sourceName="Sample" sourceVersion="14.0.1" device="&lt;&lt;HKDevice: 0x2811a54f0&gt;, name:iPhone, manufacturer:Apple Inc., model:iPhone, hardware:iPhone12,3, software:14.0.1&gt;" unit="%" creationDate="2020-10-01 19:42:12 -0800" startDate="2020-10-01 13:43:31 -0800" endDate="2020-10-01 13:44:29 -0800" value="0">
  <MetadataEntry key="HKMetadataKeyDevicePlacementSide" value="1"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierWalkingAsymmetryPercentage" sourceName="Sample" sourceVersion="14.0.1" device="&lt;&lt;HKDevice: 0x2811a54f0&gt;, name:iPhone, manufacturer:Apple Inc., model:iPhone, hardware:iPhone12,3, software:14.0.1&gt;" unit="%" creationDate="2020-10-01 19:42:12 -0800" startDate="2020-10-01 13:44:56 -0800" endDate="2020-10-01 13:49:05 -0800" value="0">
  <MetadataEntry key="HKMetadataKeyDevicePlacementSide" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierWalkingAsymmetryPercentage" sourceName="Sample" sourceVersion="14.0.1" device="&lt;&lt;HKDevice: 0x2811a54f0&gt;, name:iPhone, manufacturer:Apple Inc., model:iPhone, hardware:iPhone12,3, software:14.0.1&gt;" unit="%" creationDate="2020-10-01 19:42:12 -0800" startDate="2020-10-01 13:49:42 -0800" endDate="2020-10-01 13:50:53 -0800" value="0">
  <MetadataEntry key="HKMetadataKeyDevicePlacementSide" value="2"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierWalkingAsymmetryPercentage" sourceName="Sample" sourceVersion="14.0.1" device="&lt;&lt;HKDevice: 0x2811a54f0&gt;, name:iPhone, manufacturer:Apple Inc., model:iPhone, hardware:iPhone12,3, software:14.0.1&gt;" unit="%" creationDate="2020-10-01 19:42:12 -0800" startDate="2020-10-01 13:51:58 -0800" endDate="2020-10-01 13:52:15 -0800" value="0">
  <MetadataEntry key="HKMetadataKeyDevicePlacementSide" value="2"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierWalkingAsymmetryPercentage" sourceName="Sample" sourceVersion="14.0.1" device="&lt;&lt;HKDevice: 0x2811a54f0&gt;, name:iPhone, manufacturer:Apple Inc., model:iPhone, hardware:iPhone12,3, software:14.0.1&gt;" unit="%" creationDate="2020-10-01 19:42:12 -0800" startDate="2020-10-01 13:52:32 -0800" endDate="2020-10-01 13:53:56 -0800" value="0">
  <MetadataEntry key="HKMetadataKeyDevicePlacementSide" value="2"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierWalkingAsymmetryPercentage" sourceName="Sample" sourceVersion="14.0.1" device="&lt;&lt;HKDevice: 0x2811a54f0&gt;, name:iPhone, manufacturer:Apple Inc., model:iPhone, hardware:iPhone12,3, software:14.0.1&gt;" unit="%" creationDate="2020-10-01 19:42:12 -0800" startDate="2020-10-01 13:57:34 -0800" endDate="2020-10-01 13:59:12 -0800" value="0">
  <MetadataEntry key="HKMetadataKeyDevicePlacementSide" value="2"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierWalkingAsymmetryPercentage" sourceName="Sample" sourceVersion="14.0.1" device="&lt;&lt;HKDevice: 0x2811a54f0&gt;, name:iPhone, manufacturer:Apple Inc., model:iPhone, hardware:iPhone12,3, software:14.0.1&gt;" unit="%" creationDate="2020-10-01 19:42:12 -0800" startDate="2020-10-01 14:04:40 -0800" endDate="2020-10-01 14:08:05 -0800" value="0">
  <MetadataEntry key="HKMetadataKeyDevicePlacementSide" value="2"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierWalkingAsymmetryPercentage" sourceName="Sample" sourceVersion="14.0.1" device="&lt;&lt;HKDevice: 0x2811a54f0&gt;, name:iPhone, manufacturer:Apple Inc., model:iPhone, hardware:iPhone12,3, software:14.0.1&gt;" unit="%" creationDate="2020-10-01 19:42:12 -0800" startDate="2020-10-01 14:08:49 -0800" endDate="2020-10-01 14:09:32 -0800" value="0.04">
  <MetadataEntry key="HKMetadataKeyDevicePlacementSide" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierWalkingAsymmetryPercentage" sourceName="Sample" sourceVersion="14.0.1" device="&lt;&lt;HKDevice: 0x2811a54f0&gt;, name:iPhone, manufacturer:Apple Inc., model:iPhone, hardware:iPhone12,3, software:14.0.1&gt;" unit="%" creationDate="2020-10-01 19:42:12 -0800" startDate="2020-10-01 14:10:52 -0800" endDate="2020-10-01 14:11:14 -0800" value="0">
  <MetadataEntry key="HKMetadataKeyDevicePlacementSide" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierWalkingAsymmetryPercentage" sourceName="Sample" sourceVersion="14.0.1" device="&lt;&lt;HKDevice: 0x2811a54f0&gt;, name:iPhone, manufacturer:Apple Inc., model:iPhone, hardware:iPhone12,3, software:14.0.1&gt;" unit="%" creationDate="2020-10-01 19:42:12 -0800" startDate="2020-10-01 14:45:27 -0800" endDate="2020-10-01 14:46:50 -0800" value="0">
  <MetadataEntry key="HKMetadataKeyDevicePlacementSide" value="2"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierWalkingAsymmetryPercentage" sourceName="Sample" sourceVersion="14.0.1" device="&lt;&lt;HKDevice: 0x2811a54f0&gt;, name:iPhone, manufacturer:Apple Inc., model:iPhone, hardware:iPhone12,3, software:14.0.1&gt;" unit="%" creationDate="2020-10-01 19:42:12 -0800" startDate="2020-10-01 14:48:02 -0800" endDate="2020-10-01 14:48:59 -0800" value="0">
  <MetadataEntry key="HKMetadataKeyDevicePlacementSide" value="2"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierWalkingAsymmetryPercentage" sourceName="Sample" sourceVersion="14.0.1" device="&lt;&lt;HKDevice: 0x2811a54f0&gt;, name:iPhone, manufacturer:Apple Inc., model:iPhone, hardware:iPhone12,3, software:14.0.1&gt;" unit="%" creationDate="2020-10-01 19:42:12 -0800" startDate="2020-10-01 14:56:34 -0800" endDate="2020-10-01 14:57:06 -0800" value="0">
  <MetadataEntry key="HKMetadataKeyDevicePlacementSide" value="2"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierWalkingAsymmetryPercentage" sourceName="Sample" sourceVersion="14.0.1" device="&lt;&lt;HKDevice: 0x2811a54f0&gt;, name:iPhone, manufacturer:Apple Inc., model:iPhone, hardware:iPhone12,3, software:14.0.1&gt;" unit="%" creationDate="2020-10-01 19:42:12 -0800" startDate="2020-10-01 14:57:17 -0800" endDate="2020-10-01 14:57:55 -0800" value="0">
  <MetadataEntry key="HKMetadataKeyDevicePlacementSide" value="2"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierWalkingAsymmetryPercentage" sourceName="Sample" sourceVersion="14.0.1" device="&lt;&lt;HKDevice: 0x2811a54f0&gt;, name:iPhone, manufacturer:Apple Inc., model:iPhone, hardware:iPhone12,3, software:14.0.1&gt;" unit="%" creationDate="2020-10-01 19:42:12 -0800" startDate="2020-10-01 14:58:26 -0800" endDate="2020-10-01 14:59:11 -0800" value="0">
  <MetadataEntry key="HKMetadataKeyDevicePlacementSide" value="1"/>
 </Record>